"""empty message

Revision ID: 742a96d65f85
Revises: 47dfff54245a
Create Date: 2022-05-17 07:59:18.653455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742a96d65f85'
down_revision = '47dfff54245a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
